---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bowencen/innerdynamiccoaching
    - /bin/cp -r css $DEPLOYPATH/
    - /bin/cp -r js $DEPLOYPATH/
    - /bin/cp -r images $DEPLOYPATH/
    - /bin/cp -r font $DEPLOYPATH/
    - /bin/cp -r includes $DEPLOYPATH/
    - /bin/cp *.php $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp robots.txt $DEPLOYPATH/
    - /bin/cp sitemap.xml $DEPLOYPATH/
